---
  - name: rabbitmq default file
    template:
      src: "{{ config_file.src }}"
      dest: "{{ config_file.dest }}"
      owner: root
      group: root
      mode: 0644
    with_items:
      - { src: ../templates/etc/default/rabbitmq-server.j2 , dest: /etc/default/rabbitmq-server }
      - { src: ../templates/etc/rabbitmq/rabbitmq.config.j2, dest: /etc/rabbitmq/rabbitmq.config }
      - { src: ../templates/etc/rabbitmq/rabbitmq-env.conf.j2, dest: /etc/rabbitmq/rabbitmq-env.conf }
    loop_control:
      loop_var: config_file
    notify:
      restart rabbitmq-server

  - name: Enable the plugins is installed
    rabbitmq_plugin:
      names: "{{ plugin }}"
      prefix: /usr/lib/rabbitmq
      state: enabled
      new_only: yes
    with_items: "{{ rabbitmq_plugins }}"
    loop_control:
      loop_var: plugin
    notify:
      restart rabbitmq-server
