---
  - name: check if ha-mode is already enabled
    shell: rabbitmqctl list_policies
    register: list_policies
    changed_when: false
    delegate_to: "{{ hostvars[groups['cluster'][0]]['inventory_hostname'] }}"
    run_once: true

  - name: set ha-mode to exactly two nodes for all queues for backup
    shell: rabbitmqctl set_policy ha-exactly-two ".*" '{"ha-mode":"exactly","ha-params":2,"ha-sync-mode":"automatic"}'
    register: res
    failed_when: res.rc != 0
    when: list_policies.stdout.find("ha-exactly-two") == -1
    delegate_to: "{{ hostvars[groups['cluster'][0]]['inventory_hostname'] }}"
    run_once: true
